lib/coin_rates_web/router.ex
defmodule CoinRatesWeb.Router do
  use CoinRatesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CoinRatesWeb.Plugs.SetCurrentUser
    plug CoinRatesWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :session do
    plug :put_layout, { CoinRatesWeb.LayoutView, :session}
  end

  pipeline :auth do
    plug CoinRatesWeb.Plugs.AuthenticateUser
  end

  scope "/", CoinRatesWeb do
    pipe_through [:browser, :auth]

    get "/", Plugs.Redirect, to: "/dashboard"
    get "/dashboard", CoinsController, :index

    resources "/coins", CoinsController, except: [:index, :show]
  end

  scope "/session/", CoinRatesWeb do
    pipe_through [:browser, :session]

    resources "/registrations", RegistrationController, only: [:new, :create]

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", CoinRatesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/live-dashboard", metrics: CoinRatesWeb.Telemetry
    end
  end
end

lib/coin_rates_web/views/layout_view.ex
defmodule CoinRatesWeb.LayoutView do
  use CoinRatesWeb, :view

  def title do
    "Coin Rates Dashboard"
  end
end

lib/coin_rates_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CoinRates · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <p>Locale: <%= @locale %></p>
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/coin_rates_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title() %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>

      <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
            <a class="navbar-brand" href="#">Coin Dashboard</a>
            <div>
              <%= if @user_signed_in? do %>
                <%= @current_user.email %>
                <%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary my-2 my-sm-0"  %>
              <% else %>
                <%= link "Login", to: "/session/login" %>
                <%= link "Register", to: Routes.registration_path(@conn, :new), class: "btn btn-outline-success my-2 my-sm-0" %>
              <% end %>
            </div>
            
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <%= if get_flash(@conn, :info) do %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <%= get_flash(@conn, :info) %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= get_flash(@conn, :error) %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/coin_rates_web/templates/layout/live.html.leex
<p><%= live_flash(@flash, :notice) %></p>
<p><%= live_flash(@flash, :error) %></p>
<%= @inner_content %>

lib/coin_rates_web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title() %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body class="text-center">
    <main role="main" class="session-form">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <%= @inner_content %>

      <div class="mt-2">
        <%= if @conn.request_path == "/session/login" do %>
          <%= link "Register", to: Routes.registration_path(@conn, :new) %>
        <%= else %>
          <%= link "Login", to: "/session/login" %>
        <% end %>
      </div>
    </main>
  </body>
</html>